CBP-26972 Extend register-build-artifact to support multiple artifact URLs

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -11,7 +11,7 @@ inputs:
     description: 'The version of the artifact.'
     required: true
   url:
-    description: 'The url where the artifact version is located e.g. docker.io/myapp/myimg:1.0.0.'
+    description: 'The url where the artifact version is located e.g. docker.io/myapp/myimg:1.0.0. Formatted as a comma-separated list for passing multiple artifacts.'
     required: true
   digest:
     description: 'The artifact digest that uniquely and immutably identifies the artifact.'
@@ -37,7 +37,10 @@ inputs:
 outputs:
   artifact-id:
     value: ${{ steps.registerBuildArtifact.outputs.artifact-id }}
-    description: "The unique identifier of the artifact."
+    description: "The unique identifier of the artifact. If multiple artifacts are registered, this will be the ID of the first one."
+  artifact-ids:
+    value: ${{ steps.registerBuildArtifact.outputs.artifact-ids }}
+    description: "The unique identifiers in JSON format of the artifacts when multiple are registered."
 
 runs:
   using: composite
@@ -82,70 +85,80 @@ runs:
           echo "+----------------------+----------------------------------------------------+"        
         }
         
-        # Create the payload JSON file
-        echo '{ "runId": "'"$CLOUDBEES_RUN_ID"'", "runAttempt": "'"$CLOUDBEES_RUN_ATTEMPT"'",' > /tmp/payload.json 
-        echo '"name": "'"$INPUT_NAME"'", "url": "'"$INPUT_URL"'", "version": "'"$INPUT_VERSION"'" ' >> /tmp/payload.json
-
-         # Add the commit info if commit sha is provided
-        if [ -n "$INPUT_COMMIT" ];
-        then       
-          echo ',  "commit" : {' >> /tmp/payload.json
-          echo '    "repositoryUrl": "'"$INPUT_REPOSITORY_URL"'",' >> /tmp/payload.json
-          echo '    "commitId": "'"$INPUT_COMMIT"'",' >> /tmp/payload.json
-          echo '    "ref": "'"$INPUT_REF"'"' >> /tmp/payload.json
-          echo '  }' >> /tmp/payload.json
-        fi
-
-        # Add the digest parameter if provided
-        if [ -n "$INPUT_DIGEST" ]; 
-        then
-          echo ', "digest": "'"$INPUT_DIGEST"'"' >> /tmp/payload.json
-        fi
-
-        # Add the labels parameter if provided
-        if [ -n "$INPUT_LABELS" ]; 
-        then
-         # Convert labels to JSON array format
-         formatted_labels=$(echo "$INPUT_LABELS" | sed -e 's/[][]//g' | awk -v RS=, -v ORS=, '{ gsub(/^[ \t\r\n]+|[ \t\r\n]+$/, "");  gsub(/\\"/, "\\\\\""); gsub(/"/, "\\\""); printf "\"%s\",", $0 }' | sed 's/,$//' | sed 's/^/[/; s/$/]/')
-         echo ', "labels": '"$formatted_labels">> /tmp/payload.json
-        fi
+        registered_ids=()
+        # Split the input string url by comma separator to use them in loop to register multiple artifacts
+        IFS=',' read -ra URLS <<< "$INPUT_URLS"
+        for inputUrl in "${URLS[@]}"; do
+          inputUrl=$(echo "$inputUrl" | xargs)  # Trim whitespace
+                  
+          # Create the payload JSON file
+          echo '{ "runId": "'"$CLOUDBEES_RUN_ID"'", "runAttempt": "'"$CLOUDBEES_RUN_ATTEMPT"'",' > /tmp/payload.json 
+          echo '"name": "'"$INPUT_NAME"'", "url": "'"$inputUrl"'", "version": "'"$INPUT_VERSION"'" ' >> /tmp/payload.json
+  
+           # Add the commit info if commit sha is provided
+          if [ -n "$INPUT_COMMIT" ];
+          then       
+            echo ',  "commit" : {' >> /tmp/payload.json
+            echo '    "repositoryUrl": "'"$INPUT_REPOSITORY_URL"'",' >> /tmp/payload.json
+            echo '    "commitId": "'"$INPUT_COMMIT"'",' >> /tmp/payload.json
+            echo '    "ref": "'"$INPUT_REF"'"' >> /tmp/payload.json
+            echo '  }' >> /tmp/payload.json
+          fi
+  
+          # Add the digest parameter if provided
+          if [ -n "$INPUT_DIGEST" ]; 
+          then
+            echo ', "digest": "'"$INPUT_DIGEST"'"' >> /tmp/payload.json
+          fi
+  
+          # Add the labels parameter if provided
+          if [ -n "$INPUT_LABELS" ]; 
+          then
+           # Convert labels to JSON array format
+           formatted_labels=$(echo "$INPUT_LABELS" | sed -e 's/[][]//g' | awk -v RS=, -v ORS=, '{ gsub(/^[ \t\r\n]+|[ \t\r\n]+$/, "");  gsub(/\\"/, "\\\\\""); gsub(/"/, "\\\""); printf "\"%s\",", $0 }' | sed 's/,$//' | sed 's/^/[/; s/$/]/')
+           echo ', "labels": '"$formatted_labels">> /tmp/payload.json
+          fi
+          
+          # Add the componentId parameter if provided
+          if [ -n "$INPUT_COMPONENT_ID" ];
+          then
+            echo ', "componentId": "'"$INPUT_COMPONENT_ID"'"' >> /tmp/payload.json
+          fi
+          echo ' }' >> /tmp/payload.json
+  
+          # Display the generated payload
+          echo "Request payload:"
+          print_inputs
+          
+          # Make CloudBees Unify API call to create artifact_info record
+          response=$(curl --retry 5 --retry-delay 10 --retry-all-errors --silent --show-error --fail-with-body \
+            -X 'POST' "$URL/v3/artifactinfos" \
+            -H "Authorization: Bearer $JWT" \
+            -H 'Content-Type: application/json' \
+            --data-binary '@/tmp/payload.json') || command_failed=1
+          
+          # Check if the API call failed
+          if [ ${command_failed:-0} -eq 1 ];
+          then
+            echo "CloudBees Unify API call failed with error: $response"
+            exit 1
+          fi
+          
+          # If successful, show the response nicely
+          echo ""
+          echo "CloudBees Unify API success response:"
+          echo "$response" | /usr/bin/jq || echo "$response"
+          
+          # Extract the artifactId
+          id=$(echo "$response" | grep -o '"id": *"[^"]*"' | sed 's/.*"id": *"\([^"]*\)".*/\1/')
+          registered_ids+=("$id")
+        done
         
-        # Add the componentId parameter if provided
-        if [ -n "$INPUT_COMPONENT_ID" ];
-        then
-          echo ', "componentId": "'"$INPUT_COMPONENT_ID"'"' >> /tmp/payload.json
-        fi
-        echo ' }' >> /tmp/payload.json
-
-        # Display the generated payload
-        echo "Request payload:"
-        print_inputs
+        # Set the single registered ID as output (the first one if multiple)
+        printf %s "${registered_ids[0]}" > $CLOUDBEES_OUTPUTS/artifact-id
         
-        # Make CloudBees Unify API call to create artifact_info record
-        response=$(curl --retry 5 --retry-delay 10 --retry-all-errors --silent --show-error --fail-with-body \
-          -X 'POST' "$URL/v3/artifactinfos" \
-          -H "Authorization: Bearer $JWT" \
-          -H 'Content-Type: application/json' \
-          --data-binary '@/tmp/payload.json') || command_failed=1
-        
-        # Check if the API call failed
-        if [ ${command_failed:-0} -eq 1 ];
-        then
-          echo "CloudBees Unify API call failed with error: $response"
-          exit 1
-        fi
-        
-        # If successful, show the response nicely
-        echo ""
-        echo "CloudBees Unify API success response:"
-        echo "$response" | /usr/bin/jq || echo "$response"
-        
-        # Extract the artifactId
-        id=$(echo "$response" | grep -o '"id": *"[^"]*"' | sed 's/.*"id": *"\([^"]*\)".*/\1/')
-        
-        # Set it as an output
-        printf %s "$id" > $CLOUDBEES_OUTPUTS/artifact-id
-
+        # Set the list of registered IDs as a JSON array output
+        printf '%s\n' "${registered_ids[@]}" | /usr/bin/jq -R . | /usr/bin/jq -s . > $CLOUDBEES_OUTPUTS/artifact-ids
       env:
         JWT: ${{ cloudbees.api.token }}
         URL: ${{ cloudbees.api.url }}
